spring:
  application:
    name: music-service
  webflux:
    multipart:
      max-in-memory-size: 20MB
  kafka:
    bootstrap-servers: 192.168.1.10:29092, 192.168.1.10:29093,192.168.1.10:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    properties:
      compression.type: lz4
      max.request.size: 20000000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
      properties:
        fetch.max.bytes: 20000000
        max.partition.fetch.bytes: 20000000
  r2dbc:
    url: r2dbc:mysql://${DB_URL:192.168.1.10}:${DB_PORT:3306}/${DB_NAME:mupl_music}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  sql:
    init:
      platform: mysql
  logging:
    level:
      org.springframework.r2dbc: DEBUG
server:
  port: 11000

minio:
  host: ${MINIO_HOST:http://192.168.1.10:10000}
  access-key: ${MINIO_ACCESS_KEY:kIlhwnt7Za2rPDKk2UUi}
  secret-key: ${MINIO_SECRET_KEY:t1NHe7LpHLJEVfRO63YJmbebpkzM029HOErnMCib}

services:
  playlist-service: ${PLAYLIST_SERVICE:http://localhost:12000}
#debug: true