spring:
  application:
    name: music-service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:192.168.1.10:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    properties:
      compression.type: lz4
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  r2dbc:
    url: r2dbc:mysql://${DB_URL:192.168.1.10}:${DB_PORT:3306}/${DB_NAME:mupl_music}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  sql:
    init:
      platform: mysql
  logging:
    level:
      org.springframework.r2dbc: DEBUG
server:
  port: 11000

minio:
  host: ${MINIO_HOST:http://192.168.1.10:10000}
  access-key: ${MINIO_ACCESS_KEY:kIlhwnt7Za2rPDKk2UUi}
  secret-key: ${MINIO_SECRET_KEY:t1NHe7LpHLJEVfRO63YJmbebpkzM029HOErnMCib}

debug: true